# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [noom, gold]
patreon: # Replace with a single Patreon username https://www.patreon.com/posts/22854182
open_collective: # Replace with a single Open Collective username tornado.io
ko_fi: # Replace with a single Ko-fi username Charlie 
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/audiosmack
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username KFC
issuehunt: # Replace with a single IssueHunt username McDonald's
otechie: # Replace with a single Otechie username justinfamily
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://moby.com' 'https://cityyear.org' https://Marlboro.com' 'https://iab.com' 'https://justinfamily.family.blog' 'https://luvs.com', 'https://www.thelostogle.com/2020/03/16/convenience-score-winning-big-at-loves-travel-stop-casino-in-newcastle/' https://g.page/justinsmith33583, Https://g.page/testing35]
